/*
import 'package:flutter/material.dart';
var list = [
  "iPhone 13 Pro 128GB",
  "iPhone 13 Pro 256GB",
  "iPhone 13 256GB",
  "iPhone 13 mini 256GB",
  "iPhone 13 128GB",
  "iPhone 12 Pro 128GB",
  "Apple iPhone 12 Pro Max 128GB",
  "Apple iPhone X"
];
var IphoneList = [
  {"Product ID": 7631,
    "Price": 24.99,
    "Retail Price": 34.99,
    "Name" : 'iPhone 13 Pro 128GB',
    "Model" : 'Apple iPhone 13 PRO',
    "Network": 'GSM / CDMA / HSPA / EVDO / LTE/ 5G',
    "Body": '146.7 x 71.5 x 7.7 mm (5.78 x 2.81 x 0.30 in)',
    "Weight": '204 g (7.20 oz)',
    "Build": 'Glass front (Gorilla Glass), glass back (Gorilla Glass), stainless steel frame',
    "SIM": 'Single SIM (Nano-SIM and/or eSIM)',
    "Display": 'Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 1000 nits (typ), 1200 nits (peak)',
    "Size": '6.1 inches, 90.2 cm2(~86.0% screen-to-body ratio)',
    "Resolution":'1170 x 2532 pixels, 19.5:9 ratio (~460 ppi density)',
    "Protection": 'Scratch-resistaScratch-resistant ceramic glass, oleophobic coating, Wide color gamut, True-tone',
    "Platform": 'iOS 15, upgradeable',
    "Chipset": 'Apple A15 Bionic (5 nm)',
    "CPU": 'Hexa-core (2 + 4)',
    "GPU": 'Apple GPU (4-core graphics)',
    "Internal Memory":'128GB 6GB RAM',
    "Main Camera": '12 MP, f/1.5, 26mm (wide), 1.9µm, dual pixel PDAF, sensor-shift stabilization (IBIS), 12 MP, f/2.8, 77mm (telephoto), PDAF, OIS, 3x optical zoom',
    "Features": 'Dual-LED dual-tone flash, HDR (photo/panorama)',
    "Video":' 4K@24/30/60fps, 1080p@30/60/120/240fps, 10bit HDR, Dolby Vision HDR (up to 60fps), ProRes, Cinematic mode, stereo sound rec.',
    "Selfie Camera": '12 MP, f/2.2, 23mm (wide), 1/3.6", SL 3D, (depth/biometrics sensor)',
    'Features': 'HDR',
    "Video": '4K@24/30/60fps, 1080p@30/60/120fps, gyro-EIS',
    "Sound":'Yes, with stereo speakers',
    "COMMS": 'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, hotspot',
    "Bluetooth": '5.0, A2DP, LE',
    "GPS": 'Yes, with A-GPS, GLONASS, GALILEO, QZSS USB Lightning, USB 2.0',
    "Features": 'Face ID, accelerometer, gyro, proximity, compass, barometer Siri natural language commands and dictation, Ultra Wideband (UWB) support',
    "Battery": 'Li-Ion 3268 mAh, non-removable (12.78 Wh)',
    "Charging": 'Fast charging 20W, 50% in 30 min',
  },{
    "Name" : 'iPhone 13 Pro 256GB',
    "Model" : 'Apple iPhone 13 PRO',
    "Network": 'GSM / CDMA / HSPA / EVDO / LTE/ 5G',
    "Body": '146.7 x 71.5 x 7.7 mm (5.78 x 2.81 x 0.30 in)',
    "Weight": '204 g (7.20 oz)',
    "Build": 'Glass front (Gorilla Glass), glass back (Gorilla Glass), stainless steel frame',
    "SIM": 'Single SIM (Nano-SIM and/or eSIM)',
    "Display": 'Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 1000 nits (typ), 1200 nits (peak)',
    "Size": '6.1 inches, 90.2 cm2(~86.0% screen-to-body ratio)',
    "Resolution":'1170 x 2532 pixels, 19.5:9 ratio (~460 ppi density)',
    "Protection": 'Scratch-resistaScratch-resistant ceramic glass, oleophobic coating, Wide color gamut, True-tone',
    "Platform": 'iOS 15, upgradeable',
    "Chipset": 'Apple A15 Bionic (5 nm)',
    "CPU": 'Hexa-core (2 + 4)',
    "GPU": 'Apple GPU (4-core graphics)',
    "Internal Memory":'256GB 6GB RAM',
    "Main Camera": '12 MP, f/1.5, 26mm (wide), 1.9µm, dual pixel PDAF, sensor-shift stabilization (IBIS), 12 MP, f/2.8, 77mm (telephoto), PDAF, OIS, 3x optical zoom',
    "Features": 'Dual-LED dual-tone flash, HDR (photo/panorama)',
    "Video":' 4K@24/30/60fps, 1080p@30/60/120/240fps, 10bit HDR, Dolby Vision HDR (up to 60fps), ProRes, Cinematic mode, stereo sound rec.',
    "Selfie Camera": '12 MP, f/2.2, 23mm (wide), 1/3.6", SL 3D, (depth/biometrics sensor)',
    'Features': 'HDR',
    "Video": '4K@24/30/60fps, 1080p@30/60/120fps, gyro-EIS',
    "Sound":'Yes, with stereo speakers',
    "COMMS": 'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, hotspot',
    "Bluetooth": '5.0, A2DP, LE',
    "GPS": 'Yes, with A-GPS, GLONASS, GALILEO, QZSS USB Lightning, USB 2.0',
    "Features": 'Face ID, accelerometer, gyro, proximity, compass, barometer Siri natural language commands and dictation, Ultra Wideband (UWB) support',
    "Battery": 'Li-Ion 3268 mAh, non-removable (12.78 Wh)',
    "Charging": 'Fast charging 20W, 50% in 30 min',
  },{
    "Name" : 'iPhone 13 256GB',
    "Model" : 'Apple iPhone 13',
    "Network": 'GSM / CDMA / HSPA / EVDO / LTE/ 5G',
    "Body": '146.7 x 71.5 x 7.7 mm (5.78 x 2.81 x 0.30 in)',
    "Weight": '174 g (6.14 oz)',
    "Build": 'Glass front (Gorilla Glass), glass back (Gorilla Glass), stainless steel frame',
    "SIM": 'Single SIM (Nano-SIM and/or eSIM)',
    "Display": 'Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 1000 nits (typ), 1200 nits (peak)',
    "Size": '6.1 inches, 90.2 cm2(~86.0% screen-to-body ratio)',
    "Resolution":'1170 x 2532 pixels, 19.5:9 ratio (~460 ppi density)',
    "Protection": 'Scratch-resistaScratch-resistant ceramic glass, oleophobic coating, Wide color gamut, True-tone',
    "Platform": 'iOS 15.0, upgradeable',
    "Chipset": 'Apple A15 Bionic (5 nm)',
    "CPU": 'Hexa-core (2 + 4)',
    "GPU": 'Apple GPU (4-core graphics)',
    "Internal Memory":'128GB 6GB RAM',
    "Main Camera": '12 MP, f/1.6, 26mm (wide), 1.7Âµm, dual pixel PDAF, sensor-shift stabilization (IBIS), 12 MP, f/2.4, 120, 13mm (ultrawide)',
    "Features": 'Dual-LED dual-tone flash, HDR (photo/panorama)',
    "Video":' 4K@24/30/60fps, 1080p@30/60/120/240fps, 10bit HDR, Dolby Vision HDR (up to XXfps), stereo sound rec.',
    "Selfie Camera": '12 MP, f/2.2, 23mm (wide), 1/3.6", SL 3D, (depth/biometrics sensor)',
    'Features': 'HDR',
    "Video": '4K@24/30/60fps, 1080p@30/60/120fps, gyro-EIS',
    "Sound":'Yes, with stereo speakers',
    "COMMS": 'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, hotspot',
    "Bluetooth": '5.0, A2DP, LE',
    "GPS": 'Yes, with A-GPS, GLONASS, GALILEO, QZSS USB Lightning, USB 2.0',
    "Features": 'Face ID, accelerometer, gyro, proximity, compass, barometer Siri natural language commands and dictation, Ultra Wideband (UWB) support',
    "Battery": ' Li-Ion 3015 mAh, non-removable (10.78 Wh)',
    "Charging": 'Fast charging 20W, 50% in 30 min',
  },{"Name" : 'iPhone 13 mini 256GB',
    "Model" : 'Apple iPhone 13 mini',
    "Network": 'GSM / CDMA / HSPA / EVDO / LTE/ 5G',
    "Body": '146.7 x 71.5 x 7.7 mm (5.78 x 2.81 x 0.30 in)',
    "Weight": '141 g (4.97 oz)',
    "Build": 'Glass front (Gorilla Glass), glass back (Gorilla Glass), stainless steel frame',
    "SIM": 'Single SIM (Nano-SIM and/or eSIM)',
    "Display": 'Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (typ), 1200 nits (peak)',
    "Size": '5.4 inches, 71.9 cm2(~85.1% screen-to-body ratio)',
    "Resolution":'1080 x 2340 pixels, 19.5:9 ratio (~476 ppi density)',
    "Protection": 'Scratch-resistaScratch-resistant ceramic glass, oleophobic coating, Wide color gamut, True-tone',
    "Platform": 'iOS 15.0, upgradeable',
    "Chipset": 'Apple A15 Bionic (5 nm)',
    "CPU": 'Hexa-core (2 + 4)',
    "GPU": 'Apple GPU (4-core graphics)',
    "Internal Memory":'256GB 4GB RAM',
    "Main Camera": '12 MP, f/1.6, 26mm (wide), 1.7µm, dual pixel PDAF, sensor-shift stabilization (IBIS), 12 MP, f/2.4, 120, 13mm (ultrawide)',
    "Features": 'Dual-LED dual-tone flash, HDR (photo/panorama)',
    "Video":' 4K@24/30/60fps, 1080p@30/60/120/240fps, 10bit HDR, Dolby Vision HDR (up to XXfps), stereo sound rec.',
    "Selfie Camera": '12 MP, f/2.2, 23mm (wide), 1/3.6", SL 3D, (depth/biometrics sensor)',
    'Features': 'HDR',
    "Video": '4K@24/30/60fps, 1080p@30/60/120fps, gyro-EIS',
    "Sound":'Yes, with stereo speakers',
    "COMMS": 'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, hotspot',
    "Bluetooth": '5.0, A2DP, LE',
    "GPS": 'Yes, with A-GPS, GLONASS, GALILEO, QZSS USB Lightning, USB 2.0',
    "Features": 'Face ID, accelerometer, gyro, proximity, compass, barometer Siri natural language commands and dictation, Ultra Wideband (UWB) support',
    "Battery": 'Li-Ion 3015 mAh, non-removable (10.78 Wh)',
    "Charging": 'Fast charging 20W, 50% in 30 min',
  },{"Name" : 'iPhone 13 128GB',
    "Model" : 'Apple iPhone 13',
    "Network": 'GSM / CDMA / HSPA / EVDO / LTE/ 5G',
    "Body": '146.7 x 71.5 x 7.7 mm (5.78 x 2.81 x 0.30 in)',
    "Weight": '174 g (6.14 oz)',
    "Build": 'Glass front (Gorilla Glass), glass back (Gorilla Glass), aluminum frame',
    "SIM": 'Single SIM (Nano-SIM and/or eSIM)',
    "Display": 'Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 800 nits (typ), 1200 nits (peak)',
    "Size": '6.1 inches, 90.2 cm2(~86.0% screen-to-body ratio)',
    "Resolution":'1170 x 2532 pixels, 19.5:9 ratio (~460 ppi density)',
    "Protection": 'Scratch-resistaScratch-resistant ceramic glass, oleophobic coating, Wide color gamut, True-tone',
    "Platform": 'iOS 15.0, upgradeable',
    "Chipset": 'Apple A15 Bionic (5 nm)',
    "CPU": 'Hexa-core (2 + 4)',
    "GPU": 'Apple GPU (4-core graphics)',
    "Internal Memory":'128GB 4GB RAM',
    "Main Camera": '12 MP, f/1.6, 26mm (wide), 1.7µm, dual pixel PDAF, sensor-shift stabilization (IBIS), 12 MP, f/2.4, 120,13mm (ultrawide)',
    "Features": 'Dual-LED dual-tone flash, HDR (photo/panorama)',
    "Video":' 4K@24/30/60fps, 1080p@30/60/120/240fps, HDR, Dolby Vision HDR (up to XXfps), stereo sound rec.',
    "Selfie Camera": '12 MP, f/2.2, 23mm (wide), 1/3.6", SL 3D, (depth/biometrics sensor)',
    'Features': 'HDR',
    "Video": '4K@24/30/60fps, 1080p@30/60/120fps, gyro-EIS',
    "Sound":'Yes, with stereo speakers',
    "COMMS": 'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, hotspot',
    "Bluetooth": '5.0, A2DP, LE',
    "GPS": 'Yes, with A-GPS, GLONASS, GALILEO, QZSS USB Lightning, USB 2.0',
    "Features": 'Face ID, accelerometer, gyro, proximity, compass, barometer Siri natural language commands and dictation, Ultra Wideband (UWB) support',
    "Battery": 'Li-Ion 3015 mAh, non-removable (10.78 Wh)',
    "Charging": 'Fast charging 20W, 50% in 30 min',
  },{"Name" : 'iPhone 12 Pro 128GB',
    "Model" : 'iPhone 12 Pro 128GB',
    "Network": '',
    "Body": ' ',
    "Weight": ' ',
    "Build": 'Ceramic Shield, tougher than any smartphone glass',
    "SIM": 'Single SIM (Nano-SIM and/or eSIM)',
    "Display": '6.1-inch (15.5 cm diagonal) Super Retina XDR display',
    "Size": '6.1 inches, 90.2 cm2(~86.0% screen-to-body ratio)',
    "Resolution":'1170 x 2532 pixels, 19.5:9 ratio (~460 ppi density)',
    "Protection": 'Scratch-resistaScratch-resistant ceramic glass, oleophobic coating, Wide color gamut, True-tone',
    "Platform": ' ',
    "Chipset": 'A14 Bionic chip, the fastest chip ever in a smartphone',
    "CPU": '',
    "GPU": ' ',
    "Internal Memory":'128GB 4GB RAM',
    "Main Camera": 'Pro camera system with 12MP Ultra Wide, Wide and Telephoto cameras; 4x optical zoom range; Night mode, Deep Fusion, Smart HDR 3, Apple ProRAW, 4K Dolby Vision HDR recording',
    "Features": 'Dual-LED dual-tone flash, HDR (photo/panorama)',
    "Video":' 4K@24/30/60fps, 1080p@30/60/120/240fps, 10bit HDR, Dolby Vision HDR (up to 60fps), ProRes, Cinematic mode, stereo sound rec.',
    "Selfie Camera": '12 MP, f/2.2, 23mm (wide), 1/3.6", SL 3D, (depth/biometrics sensor)',
    'Features': 'HDR',
    "Video": '4K@24/30/60fps, 1080p@30/60/120fps, gyro-EIS',
    "Sound":'Yes, with stereo speakers',
    "COMMS": 'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, hotspot',
    "Bluetooth": '5.0, A2DP, LE',
    "GPS": 'Yes, with A-GPS, GLONASS, GALILEO, QZSS USB Lightning, USB 2.0',
    "Features": 'Supports MagSafe accessories for easy attach and faster wireless charging,Industry-leading IP68 water resistance',
    "Battery": '',
    "Charging": 'Fast charging 20W, 50% in 30 min',
  },{"Name" : 'Apple iPhone 12 Pro Max 128GB',
    "Model" : 'Apple iPhone 12 PRO MAX',
    "Network": ' ',
    "Body": ' ',
    "Weight": ' ',
    "Build": 'Ceramic Shield, tougher than any smartphone glass',
    "SIM": 'Single SIM (Nano-SIM and/or eSIM)',
    "Display": '6.7-inch (17 cm diagonal) Super Retina XDR display',
    "Size": '6.1 inches, 90.2 cm2(~86.0% screen-to-body ratio)',
    "Resolution":'1170 x 2532 pixels, 19.5:9 ratio (~460 ppi density)',
    "Protection": 'Scratch-resistaScratch-resistant ceramic glass, oleophobic coating, Wide color gamut, True-tone',
    "Platform": 'iOS 15, upgradeable',
    "Chipset": 'Apple A15 Bionic (5 nm)',
    "CPU": 'Hexa-core (2 + 4)',
    "GPU": 'Apple GPU (4-core graphics)',
    "Internal Memory":'Memory Storage Capacity 128 GB',
    "Main Camera": 'Pro camera system with 12MP Ultra Wide, Wide and Telephoto cameras; 5x optical zoom range; Night mode, Deep Fusion, Smart HDR 3, Apple ProRAW, 4K Dolby Vision HDR recording',
    "Features": 'Industry-leading IP68 water resistance,LiDAR Scanner for improved AR experiences, Night mode portraits',
    "Video":' 4K@24/30/60fps, 1080p@30/60/120/240fps, 10bit HDR, Dolby Vision HDR (up to 60fps), ProRes, Cinematic mode, stereo sound rec.',
    "Selfie Camera": '12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording',
    'Features': 'HDR',
    "Video": ' ',
    "Sound":' ',
    "COMMS": ' ',
    "Bluetooth": '5.0, A2DP, LE',
    "GPS": 'Yes, with A-GPS, GLONASS, GALILEO, QZSS USB Lightning, USB 2.0',
    "Features": 'Face ID, accelerometer, gyro, proximity, compass, barometer Siri natural language commands and dictation, Ultra Wideband (UWB) support',
    "Battery": 'Li-Ion 3268 mAh, non-removable (12.78 Wh)',
    "Charging": 'Fast charging 20W, 50% in 30 min',
  },{"Name" : 'Apple iPhone X',
    "Model" : 'Apple iPhone X',
    "Network": '2G, 3G, 4G',
    "Body": '143.6 x 70.9 x 7.7 millimeters',
    "Weight": '174 grams',
    "Build": 'Glass front (Gorilla Glass), glass back (Gorilla Glass), stainless steel frame',
    "SIM": 'Single SIM (Nano-SIM and/or eSIM)',
    "Display": '1125 x 2436 pixels (458 ppi),Dolby Vision, HDR10, 625 nits, 120Hz, true-tone, 3D Touch, wide color gamut',
    "Size": '6.1 inches, 90.2 cm2(~86.0% screen-to-body ratio)',
    "Resolution":'1170 x 2532 pixels, 19.5:9 ratio (~460 ppi density)',
    "Protection": 'Scratch-resistaScratch-resistant ceramic glass, oleophobic coating, Wide color gamut, True-tone',
    "Platform": 'iOS 11.1.1, upgradable to iOS 13.4',
    "Chipset": 'Apple A11 Bionic (10 nm)',
    "CPU": 'Hexa-core, up to 2.39 GHz',
    "GPU": 'Apple GPU (3-core graphics)',
    "Internal Memory":'64 / 256 GB (NVMe), 3GB RAM',
    "Main Camera": 'Dual 12+12 Megapixel,Ultra HD (2160p), OIS, time-lapse video with stabilization',
    "Features": 'Dual-LED dual-tone flash, HDR (photo/panorama)',
    "Video":' 4K@24/30/60fps, 1080p@30/60/120/240fps, 10bit HDR, Dolby Vision HDR (up to 60fps), ProRes, Cinematic mode, stereo sound rec.',
    "Selfie Camera": '12 MP, f/2.2, 23mm (wide), 1/3.6", SL 3D, (depth/biometrics sensor)',
    'Features': 'HDR',
    "Video": '4K@24/30/60fps, 1080p@30/60/120fps, gyro-EIS',
    "Sound":'(No 3.5mm Jack) Loudspeaker (stereo speakers)',
    "COMMS": 'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, hotspot',
    "Bluetooth": '5.0, A2DP, LE',
    "GPS": 'Yes, with A-GPS, GLONASS, GALILEO, QZSS USB Lightning, USB 2.0',
    "Features": 'Face ID, LED Flash for Alerts, gyro, proximity, compass, – Apple Pay (Visa, MasterCard, AMEX certified),Siri',
    "Battery": 'Lithium-ion 2716 mAh (non-removable)',
    "Charging": '15W Fast Charging  (50% in 30 min), Qi Wireless Charging USB Power Delivery 2.0',
  },
];

*/
